---
title: "report_rmd"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###3년치 공통 변수만 추출

```{r}
library(dplyr)
library(quantmod)
library(ggplot2)

H2015 <- read.csv("C:/Project/data/happiness_2015.csv", header = T, sep = ",")
H2016 <- read.csv("C:/Project/data/happiness_2016.csv", header = T, sep = ",")
H2017 <- read.csv("C:/Project/data/happiness_2017_Full.csv", header = T, sep = ",")

head(H2015)
head(H2016)
head(H2017)

H2015$Year <- as.factor(c("2015"))
H2016$Year <- as.factor(c("2016"))
H2017$Year <- as.factor(c("2017"))

Happiness <- rbind.data.frame(H2015[,c(13, 1, 2, 3, 4, 6:12)], H2016[,c(14, 1, 2, 3, 4, 7:13)], H2017[,c(15, 2, 3, 4, 5, 8:14)])
head(Happiness)
str(Happiness)
summary(Happiness)
```

###3년 모두 참가한 나라만 이용하여 Happiness 데이터 만들기
```{r}
Happiness <- read.csv("C:/Project/data/Happiness_Join.csv", header = T, sep = ",")

countries.didnt.appear.3years <- Happiness %>% group_by(Country) %>% mutate(count = sum(as.numeric(Year)))
countries.didnt.appear.3years %>% filter(count != 6048) %>% select(Country, Happiness_Rank, Year) %>% arrange(Country)

#3년 모두 참가한 나라
Happiness_ <- Happiness %>% filter(!(Country %in% c("Oman", "Suriname", "Somaliland Region", "Mozambique", "Lesotho", "Laos", "Swaziland", "Djibouti", "Comoros", "Central African Republic", "Belize", "Namibia", "Puerto Rico", "Somalia", "South Sudan")))
Happiness_$Year <- as.factor(Happiness_$Year)

#3년 중 하나라도 참가하지 않은 나라
Happiness_f <- Happiness %>% filter(Country %in% c("Oman", "Suriname", "Somaliland Region", "Mozambique", "Lesotho", "Laos", "Swaziland", "Djibouti", "Comoros", "Central African Republic", "Belize", "Namibia", "Puerto Rico", "Somalia", "South Sudan"))
Happiness_f$Year <- as.factor(Happiness_f$Year)
```

###EDA - 3년 동안 Happiness score Top 10 나라 확인
```{r}
Hap2015 <- Happiness_ %>% filter(Year == "2015")
Hap2016 <- Happiness_ %>% filter(Year == "2016")
Hap2017 <- Happiness_ %>% filter(Year == "2017")


Happiness_ %>% group_by(Country) %>% summarise(Country_mean=mean(Happiness_Score)) %>% arrange(desc(Country_mean)) %>% head(10)

Hap2015 %>% arrange(desc(Happiness_Score)) %>% head(10) %>% select(Country)
Hap2016 %>% arrange(desc(Happiness_Score)) %>% head(10) %>% select(Country)
Hap2017 %>% arrange(desc(Happiness_Score)) %>% head(10) %>% select(Country)

#3년동안 Top 10에 속하는 나라는 같음
#해당 나라 이름: Switzerland, Iceland, Denmark, Norway, Canada, Finland, Netherlands, Sweden, New Zealand, Australia

Happiness_10 <- Happiness_ %>% filter(Country %in% c("Switzerland", "Iceland", "Denmark", "Norway", "Canada", "Finland", "Netherlands", "Sweden", "New Zealand", "Australia"))
Happiness_10$Year <- as.factor(Happiness_10$Year)
ggplot(Happiness_10, aes(Country, Happiness_Score, group = Year)) + geom_line(aes(color = Year)) + theme_bw() + theme(axis.text.x=element_text(angle=70, hjust=1)) + labs(title = "HAPPINESS SCORE OF TOP 10 COUNTRY")
```

###EDA - 지역별 Happiness score 비교
```{r}
Happiness_ %>% group_by(Region) %>% summarise(region_mean = mean(Happiness_Score)) %>% arrange(desc(region_mean))

ggplot(Happiness_, aes(Region, Happiness_Score, group = Year)) + geom_line(aes(color = Year)) + theme_bw() + theme(axis.text.x=element_text(angle=70, hjust=1)) + labs(title = "HAPPINESS SCORE BY REGION")
```

###EDA - Continent 변수 추가, Continent - Africa, Asia, Oceania, Europe, North America, South America
```{r}
Happiness_$Continent <- ifelse(Happiness_$Region %in% c("Central and Eastern Europe", "Western Europe"), "Europe", 
                            ifelse(Happiness_$Region %in% c("Eastern Asia", "Southeastern Asia", "Southern Asia"), "Asia",
                                   ifelse(Happiness_$Region %in% c("Middle East and Northern Africa", "Sub-Saharan Africa", "South Africa"), "Africa",
                                          ifelse(Happiness_$Region %in% c("North America"), "North America",
                                                 ifelse(Happiness_$Region %in% c("Latin America and Caribbean"), "South America",
                                                        ifelse(Happiness_$Region %in% c("Australia and New Zealand"), "Oceania", FALSE))))))
```

###Correlogram 상관계수 확인
```{r}
library(corrgram)

corrgram((Happiness_ %>% filter(Continent == "Africa"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for Africa")

corrgram((Happiness_ %>% filter(Continent == "Asia"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for Asia")

corrgram((Happiness_ %>% filter(Continent == "Europe"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for Europe")

corrgram((Happiness_ %>% filter(Continent == "South America"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for South America")

corrgram((Happiness_ %>% filter(Continent == "North America"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for North America")

corrgram((Happiness_ %>% filter(Continent == "Oceania"))[,c(5:12)], order=FALSE, upper.panel=panel.cor, main="Happiness Correlation for Oceania")
```

###Scattor plot
```{r}
ggplot(Happiness_, aes(x = Economy, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Economy")

ggplot(Happiness_, aes(x = Family, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Family")

ggplot(Happiness_, aes(x = Health, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Health")

ggplot(Happiness_, aes(x = Freedom, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Freedom")

ggplot(Happiness_, aes(x = Trust, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Trust")

ggplot(Happiness_, aes(x = Generosity, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Generosity")

ggplot(Happiness_, aes(x = Dystopia_Residual, y = Happiness_Score)) + 
  geom_point(aes(color = Continent), size = 1.3, alpha = 0.9) +  
  geom_smooth(aes(color = Continent, fill = Continent), 
              method = "lm", fullrange = TRUE) +
  facet_wrap(~Continent) +
  theme_bw() + labs(title = "Scatter plot with regression line - Dystopia_Residual")
```


